name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" , "dev" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: conanio/gcc8

    steps:
    - uses: actions/checkout@v3

    - name: Configure conan
      run: conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: Configure cmake
      run: mkdir build ; (cd build && conan init .. && cmake ..)

    - name: Build
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --parallel 4

